name: DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: dotnet build
        run: dotnet build --configuration Release

      - name: dotnet test
        run: dotnet test

      - name: dotnet publish
        run: dotnet publish My.Weight.Api -c Release -o ./dist

      - name: vite build
        run: |
          cd My.Weight.Ui
          npm ci
          npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE5B8FDA46FA4A22A47B6212607D4413 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AE577088F1534A39AC400CCE0CD7EAF6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_084BE01CAAC24048A703935D73442E7E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ruslank-weight'
          slot-name: 'Production'
          package: .
